DROP TABLE IF EXISTS Contrainte CASCADE;
DROP TABLE IF EXISTS Arete CASCADE;
DROP TABLE IF EXISTS Sommet CASCADE;

CREATE TABLE Sommet (
    IdSommet SERIAL PRIMARY KEY,
    NomSommet CHAR(5) NOT NULL
);

CREATE TABLE Arete (
    IdArete SERIAL PRIMARY KEY,
    Distance INT NOT NULL,
    ptD INT NOT NULL,
    ptA INT NOT NULL,
    CONSTRAINT fk_ptD FOREIGN KEY (ptD) REFERENCES Sommet(IdSommet) ON DELETE CASCADE,
    CONSTRAINT fk_ptA FOREIGN KEY (ptA) REFERENCES Sommet(IdSommet) ON DELETE CASCADE
);

CREATE TABLE Contrainte (
    IdContrainte SERIAL PRIMARY KEY,
    Value INT NOT NULL,
    AreteId INT,
    CONSTRAINT fk_arete_contrainte FOREIGN KEY (AreteId) REFERENCES Arete(IdArete) ON DELETE CASCADE
);
