DROP TABLE IF EXISTS Contrainte CASCADE;
DROP TABLE IF EXISTS Arete CASCADE;
DROP TABLE IF EXISTS Sommet CASCADE;

CREATE TABLE Arete (
    IdArete SERIAL PRIMARY KEY,
    Distance INT NOT NULL
);

CREATE TABLE Sommet (
    IdSommet SERIAL PRIMARY KEY,
    NomSommet CHAR(5) NOT NULL,
    AreteId INT
);

ALTER TABLE Sommet
ADD CONSTRAINT fk_Arete FOREIGN KEY (AreteId) REFERENCES Arete(IdArete) ON DELETE CASCADE;

CREATE TABLE Contrainte (
    IdContrainte SERIAL PRIMARY KEY,
    Value INT NOT NULL
);
